### PR TITLE
[ZK] Blind yes/no voting

### PR DESCRIPTION
**Pull request by rlcevg**
Naive blind yes/no voting for ZeroK

### CODE REVIEW

**Comment by cleanrock** [comment]
Looks good.
Looks like this is just to display poll info and results. I am pretty sure you have tested it so I will merge it right away.

**Comment by rlcevg** [comment]
Yes, locally tested. Minor clarification on how it works:
if username is [Nightwatch](https://github.com/cleanrock/flobby/blob/6c9a2885458dc4eb74a3c1c0cfc7f238473112f5/src/gui/BattleChat.cpp#L66) and message contains ["Poll: "](https://github.com/cleanrock/flobby/blob/6c9a2885458dc4eb74a3c1c0cfc7f238473112f5/src/gui/VoteLine.cpp#L67) token then it activates yes/no buttons. If message has ["[END:"](https://github.com/cleanrock/flobby/blob/6c9a2885458dc4eb74a3c1c0cfc7f238473112f5/src/gui/VoteLine.cpp#L70) token then it deactivates buttons. Basically it PR emulates old format of the message.
BattlePoll also contains info on how many yes' and how many no's, but blind voting is more fun.

**Comment by cleanrock** [comment]
Ok, I forgot the part of the code catching Nightwatch messages, thanks for clarifying.

**Comment by lynxthecat** [comment]
What about dealing with voting for the new four-map voting structure in ZKL in which four maps are displayed and you need to vote for each one. Would it be possible to implement that?

**Comment by rlcevg** [comment]
BattlePoll message for yes/no looks like
```
{
        "MapName" : "Akilon Wastelands ZK v1",
        "MapSelection" : true,
        "NotifyPoll" : false,
        "Options" : 
        [
                {
                        "Id" : 1,
                        "Name" : "Yes",
                        "Url" : "http://zero-k.info/Maps/Detail/50426",
                        "Votes" : 0
                },
                {
                        "Id" : 2,
                        "Name" : "No",
                        "Url" : "",
                        "Votes" : 1
                }
        ],
        "Topic" : "Change map to Akilon Wastelands ZK v1?",
        "Url" : "http://zero-k.info/Maps/Detail/50426",
        "VotesToWin" : 2,
        "YesNoVote" : true
}
```
BattlePoll message for multi-vote looks like
```
{
        "MapSelection" : true,
        "NotifyPoll" : false,
        "Options" : 
        [
                {
                        "Id" : 1,
                        "Name" : "Fairyland 1.31",
                        "Url" : "http://zero-k.info/Maps/Detail/57150",
                        "Votes" : 0
                },
                {
                        "Id" : 2,
                        "Name" : "TitanDuel 2.2",
                        "Url" : "http://zero-k.info/Maps/Detail/56655",
                        "Votes" : 0
                },
                {
                        "Id" : 3,
                        "Name" : "Random Crags v0.61",
                        "Url" : "http://zero-k.info/Maps/Detail/58192",
                        "Votes" : 0
                },
                {
                        "Id" : 4,
                        "Name" : "Fields_Of_Isis",
                        "Url" : "http://zero-k.info/Maps/Detail/7404",
                        "Votes" : 0
                }
        ],
        "Topic" : "Choose the next map",
        "Url" : "",
        "VotesToWin" : 2,
        "YesNoVote" : false
}
```
Possible - must be, with altered UI (where to put those lengthy map-names?), but no interest/time atm.

EDIT: multi-vote client's reply: `!vote 1` - `!vote 4`

**Pull request merged**
